apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        imagePullPolicy: IfNotPresent
        image: dashboard-website
        ports:
        - containerPort: 8080
        env:
        - name: HOST
          value: "dashboard.com"
---
apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  selector:
    app: website
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30002